version: '3.3'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: point-of-sale-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: programwithgio-nginx
    restart: always
    ports:
      - 8001:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d